# Generated by Django 3.2.6 on 2021-09-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='curso',
        ),
    ]
