# Generated by Django 3.2.9 on 2021-11-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210906_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_fecha_hora',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_fecha',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_hora',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_conversacion',
            field=models.CharField(max_length=40000),
        ),
    ]
