# Generated by Django 3.2.6 on 2021-08-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_correo', models.CharField(max_length=40)),
                ('usuario_contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
