# Generated by Django 3.2.6 on 2021-08-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=60)),
                ('alumno_semestre', models.CharField(max_length=20)),
                ('alumno_carrera', models.CharField(max_length=40)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='usuario.usuario')),
            ],
        ),
    ]
