# Generated by Django 3.2.6 on 2021-08-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0002_alter_profesor_usuario'),
        ('alumno', '0002_alter_alumno_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nombre', models.CharField(max_length=60)),
                ('alumno', models.ManyToManyField(to='alumno.Alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.profesor')),
            ],
        ),
    ]
