# Generated by Django 3.2.6 on 2021-08-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumno',
        ),
    ]
