# Generated by Django 3.2.6 on 2021-08-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0002_alter_alumno_usuario'),
        ('profesor', '0002_alter_profesor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnocurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.profesor')),
            ],
        ),
    ]
