# Generated by Django 3.2.6 on 2021-08-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_curso_alumno'),
        ('alumnocurso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnocurso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
            preserve_default=False,
        ),
    ]
